### ISSUE TITLE
RSiteCatalyst detailed request

### ISSUE THREAD

**Issue by sylvaincop** [randyzwitch/randyzwitch.github.io#1]
Hello Randy,

I started yesterday a project regarding the extraction of Omniture data... and I found your really useful package RSiteCatalyst !

My objective is to be able to make similar reports as the ones currently done through Omniture Platform.
I succeeded, by using QueueOvertime, to get right metrics with summary by day over a defined period.
_Date             View
01/01/2016  500
01/02/2016  367
01/03/2016  435_

However, it seems I am not able with this function to breakdown the figures at a more detailed level. My objective would be to have similar results not only by day but also by Visitor_ID, emails... (variables available in Data Breakdown in Omniture Platform).

_Date                 Visitor_ID       View
01/01/2016     7767675-4D     300
01/01/2016     989767D-d      200
01/02/2016    7767675-4D     300
01/02/2016     989767D-d      67
01/03/2016    7767675-4D     200
01/03/2016     sfsfsf6565-d   235_

Could you please guide me to get such results ?

Thanks in advance,
Best regards,
Sylvain

**Comment by randyzwitch** [comment]
Hi Sylvain, glad you are finding the package useful. 

There's really no way for me to help with questions like this, as every implementation is different. All I can say is that if the report is possible in the Adobe Analytics reporting interface, then it is possible to do with RSiteCatalyst. If what you require needs data warehouse, then RSiteCatalyst won't help there as they are two different systems.

Good luck!
